apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: {{ .Release.Name }}-fastapi
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}  # force the roll deployment
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
        - name:     {{ .Release.Name }}-fastapi
          image: {{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          tag: {{ .Values.deployment.tag }}
          command: ["/bin/bash", "-c"]
          args: ["while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"]
          ports:
            - containerPort: {{ .Values.deployment.port }}
              name: fastapi
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds-2
                  key: password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds-2
                  key: user
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@{{ .Values.deployment.dbEndPoint }}:5432/{{ .Values.deployment.dbName }}